import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from 'components/layout'
import { getSession } from 'next-auth/react'
const inter = Inter({ subsets: ['latin'] })
import { Swiper, SwiperSlide } from "swiper/react";
import Image from 'next/image'
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { useWindowSize } from '@react-hook/window-size'
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import PageStructure from 'components/page-structure'

import DynamicSliderGrid from 'components/dynamic-slider-grid'
import DynamicGrid from 'components/dynamic-grid'

// function dynamicSliderGrid(data, isDesktop, isMobile) {

//   if (isDesktop === false && isMobile === false) {
//     return <></>
//   }

//   return <>

//     {data.settings.show_section_title ?
//       <div class="text-lg text-center my-3">{data.section_title}</div>
//       : ""}
//     <Swiper
//       slidesPerView={isDesktop ? data.settings.desktop.column : data.settings.mobile.column}
//       pagination={{
//         dynamicBullets: true,
//       }}
//       onPaginationHide={data.settings.show_pagination === true}
//       navigation={data.settings.navigation ? true : false}
//       modules={[Pagination, Navigation]}
//       autoplay={data.settings.autoplay ? true : false}
//       spaceBetween={20}
//       className="mySwiper mx-auto">

//       {data.section_data_array.map(sec_data => (
//         <SwiperSlide>
//           {(sec_data.desktop.image_url || sec_data.mobile.image_url) &&
//             <Link href={`/${sec_data.slug}`} >
//               <Image src={isDesktop ? sec_data.desktop.image_url : sec_data.mobile.image_url} class="mx-auto  w-full hover:bg-gray-700 h-full"
//                 height={isDesktop ? (sec_data.desktop.height ? sec_data.desktop.height : 109) : (sec_data.mobile.height ? sec_data.mobile.height : 109)}
//                 width={isDesktop ? (sec_data.desktop.width ? sec_data.desktop.width : 390) : sec_data.mobile.width ? sec_data.mobile.width : 390} /></Link>
//           }
//         </SwiperSlide>
//       ))}
//     </Swiper>
//   </>

// }


// function dynamicGrid(data, isDesktop, isMobile) {

//   if (isDesktop === false && isMobile === false) {
//     return <></>
//   }
//   return <div
//     className={((isDesktop ? data.section_title === "Main category" ? "grid-flow-col " : "" : "") + (isDesktop ? (data.settings.desktop.column > 1 ? ` grid-cols-${data.settings.desktop.column}` : "") : (data.settings.mobile.column > 1 ? ` grid-cols-${data.settings.mobile.column}` : "")) + (isDesktop ? (data.settings.desktop.row > 1 ? ` grid-rows-${data.settings.desktop.row}` : "") : (data.settings.mobile.row > 1 ? ` grid-rows-${data.settings.mobile.row}` : ""))) + " grid px-3"}>
//     {data.section_data_array.map(sec_data => (
//       ((isDesktop && sec_data.desktop.image_url) || isMobile && sec_data.mobile.image_url ?
//         <Image src={isDesktop ? sec_data.desktop.image_url : sec_data.mobile.image_url} class="w-full "
//           height={isDesktop ? (sec_data.desktop.height ? sec_data.desktop.height : 30) : (sec_data.mobile.height ? sec_data.mobile.height : 30)}
//           width={isDesktop ? (sec_data.desktop.width ? sec_data.desktop.width : 390) : (sec_data.mobile.width ? sec_data.mobile.width : 390)} />
//         : "")
//     ))}
//   </div>

// }


export default function Home() {
  // const [domLoaded, setDomLoaded] = useState(false);
  // const [width, height] = useWindowSize();

  // useEffect(() => {
  //   setDomLoaded(true);

  // }, []);


  return (
    <>
      <Head>
        <title>Life Pharmacy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0"></meta>
        <link rel="icon" href="/life-logo.jfif" />
      </Head>

      {/* <div class="font-bold text-center p-5 text-xl">Hello {session ? session.token.name : 'User'}</div> */}
      <main className={styles.main}>

        <div class=" mx-auto max-w-7xl">
         home
        </div>
      </main>


    </>
  )
}

// export async function getServerSideProps(context) {




//   //when session is available
//   const session = await getSession(context);
//   var userAddrData = {
//     data: {
//       addresses: []
//     }
//   };
//   if (session) {
//     // console.log(session.token.token);
//     // const userAddrheaders = { 'Authorization': `Bearer ${session.token.token}` };
//     const userAddrheaderRes = await fetch('https://prodapp.lifepharmacy.com/api/user/addresses', {
//       headers: {
//         Authorization: `Bearer ${session.token.token}`
//       }
//     });
//     userAddrData = await userAddrheaderRes.json();
//     // console.log(userAddrData.data.addresses);
//   }
//   return {
//     props: {
   
//       sessionServ: userAddrData.data.addresses,
    
//     }
//   }
// }
